// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-04-12 13:51:16.802538 -0500 CDT m=+0.043340601

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "info": {
        "contact": {},
        "license": {}
    },
    "paths": {
        "/v2/jobs/{id}/logs": {
            "get": {
                "description": "Retrieves logs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Jobs"
                ],
                "summary": "Retrieves logs",
                "operationId": "jobLogs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The job guid per RFC 4122",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Just to show additionalProperties work for Success",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.PropMap"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Prop": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                }
            }
        },
        "model.PropMap": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "properties": {
                    "key": {
                        "type": "string"
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
